name: Build Documentation

on:
  workflow_call:
    secrets:
      deploy_key:
        required: false

jobs:
  build_docs:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Set env vars
        run: |
          export REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}  # just the repo, as opposed to org/repo
          echo "REPOSITORY_NAME=${REPOSITORY_NAME}" >> $GITHUB_ENV

      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pixi and activate environment
        uses: prefix-dev/setup-pixi@82d477f15f3a381dbcc8adc1206ce643fe110fb7 # v0.9.3
        with:
          pixi-version: v0.60.0
          environments: docs
          cache: false
          activate-environment: docs

      - name: Test with doctest
        run: pixi run doc-tests

      - name: Build Docs
        run: pixi run build-docs

      - name: Upload HTML docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.REPOSITORY_NAME }}-docs
          path: docs/build/html/

      - name: Deploy documentation to nsls-ii.github.io
        if: github.event_name == 'release'
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501  # v3.7.3
        with:
          deploy_key: ${{ secrets.deploy_key }}
          publish_branch: master
          publish_dir: ./docs/build/html
          external_repository: NSLS-II/NSLS-II.github.io
          destination_dir: ${{ env.REPOSITORY_NAME }}
          keep_files: true  # Keep old files.
          force_orphan: false  # Keep git history.
