name: Unit Tests

on:
  workflow_call:
  workflow_dispatch:
  
jobs:
  run_tests:
    runs-on: ${{ matrix.host-os }}
    strategy:
      matrix:
        host-os: ["ubuntu-latest"]
        python-version: ["py310", "py311", "py312"]
      fail-fast: false

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Set env vars
        run: |
          export REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}  # just the repo, as opposed to org/repo
          echo "REPOSITORY_NAME=${REPOSITORY_NAME}" >> $GITHUB_ENV

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install pixi and activate environment
        uses: prefix-dev/setup-pixi@v0.8.14
        with:
          pixi-version: v0.46.0
          environments: ${{ matrix.python-version }}
          cache: false
          activate-environment: ${{ matrix.python-version }}

      - name: Run unit tests
        run: pixi run unit-tests

      - name: Run integration tests
        run: pixi run integration-tests

      - name: Test with doctest
        run: pixi run doc-tests
